# Site settings
title: Sp3kt0rZ Blog # site title
description: >- # site description
  I'll be posting my writeups on HackTheBox or anything else i find interesting.
lang: en-US # default lang
timezone: GMT+2 # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author: sp3kt0r
  name: Sphiwokuhle Shandu # author name
  bio: >- # tell to the world
    A autodidact programmer and ethical hacker who enjoys writing code that breaks into computer systems,
passionate about technology and believes his learning journey shall never end, my goal is to become a red or blue teamer
  username:  # author username
  github: https://github.com/SphiwokuhleS/
  twitter: sp3kt0r3
  facebook: 
  email: sphiwokuhleshandu24@gmail.com # your contact adress
  avatar: /assets/img/myAvatar.png # change with your own avatar

# Url settings
url: "https://sphiwokuhle-s-github-io.vercel.app/"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
