#
###################################
# Site wide configuration
####################################
#
title: Sp3kt0rZ
email:
description: A simple and awesome blog theme powered by jekyll.
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown 
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  #
###################################
# Site Owner configuration
####################################
#
owner:
  name: Sp3k0rZ
  avatar: myAvatar.png
  job: ""
  bio: "Coming soon"
  email: sphiwokuhleshandu24@gmail.com
  disqus-shortname:
  twitter: Sp3kt0r
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: SphiwokuhleS
  gitlab: #username
  stackoverflow: sphelele-shandu #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: Sphiwokuhle Shandu
  hackthebox: sp3kt0r
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
